swagger: '2.0'
info:
  title: Positions API
  description: API to retrieve the position title and numbers tied to a department and business center.
  version: '1.0'
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/positions-api
schemes:
  - https
produces:
  - application/json
paths:
  /:
    get:
      summary: Get information
      description: Build and runtime information about the application.
      parameters:
        - $ref: '#/parameters/pretty'
      responses:
        200:
          description: Object containing information
          schema:
            $ref: '#/definitions/Info'

  /positions:
    get:
      summary: List positions
      description: List position title and number tied to a business center and department.
      parameters:
        - in: query
          name: business_center
          description: "4-character business name"
          required: true
          type: string
        - in: query
          name: type
          description: The type of positions to list. Currently the API only supports "student" positions.
          required: true
          type: string
      responses:
        200:
          description: List of positions
          schema:
            $ref: "#/definitions/ResultObject"

parameters:
  pretty:
    name: pretty
    in: query
    type: boolean
    required: false
    description: If true, JSON response will be pretty-printed

definitions:
  Info:
    properties:
      name:
        type: string
        description: Name of the API.
      time:
        type: string
        description: Build time in ISO 8601 format.
      unixTime:
        type: integer
        description: Build time as milliseconds since the unix epoch.
      commit:
        type: string
        description: Git commit hash of the revision which was built.
      documentation:
        type: string
        description: Filename of the swagger specification for the API.
  Error:
    properties:
      status:
        type: integer
        description: HTTP status code.
      developerMessage:
        type: string
        description: An error string aimed at developers.
      userMesage:
        type: string
        description: An error string aimed at end users.
      code:
        type: integer
        description: Error code.
      details:
        type: string
        description: A link to further information about the error.

  ResultObject:
    properties:
      links:
        $ref: "#/definitions/Links"
      data:
        type: array
        items:
          $ref: "#/definitions/ResourceObject"

  ResourceObject:
    properties:
      id:
        type: string
      type:
        type: string
      attributes:
        $ref: "#/definitions/Attributes"
      links:
        $ref: "#/definitions/SelfLink"

  Links:
    properties:
      self:
        type: string
      first:
        type: string
      last:
        type: string
      prev:
        type: string
      next:
        type: string

  SelfLink:
    properties:
      self:
        type: string
        description: Url to this resource / location.

  Attributes:
    properties:
      title:
        type: string
        description: Position title.
      bcName:
        type: string
        description: Name of the business center
      positionNumber:
        type: string
        description: Position number
      organizationCode:
        type: string
        description: numeric orgCode for the department